// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PubHubWebServer.Data;

#nullable disable

namespace PubHubWebServer.Migrations
{
    [DbContext(typeof(PubHubDBContext))]
    [Migration("20240413081117_FixedSpellingMistake")]
    partial class FixedSpellingMistake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "71d3eda2-0069-41cc-9e76-09117bb977cd",
                            ConcurrencyStamp = "71d3eda2-0069-41cc-9e76-09117bb977cd",
                            Name = "Publisher",
                            NormalizedName = "PUBLISHER"
                        },
                        new
                        {
                            Id = "e566e2ec-825a-460b-9753-0d4525021d3a",
                            ConcurrencyStamp = "e566e2ec-825a-460b-9753-0d4525021d3a",
                            Name = "Reader",
                            NormalizedName = "READER"
                        },
                        new
                        {
                            Id = "99dd34ef-a62a-447b-9583-1e1ce6bf7723",
                            ConcurrencyStamp = "99dd34ef-a62a-447b-9583-1e1ce6bf7723",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b4665254-1122-480e-9473-7a945a0c753e",
                            RoleId = "71d3eda2-0069-41cc-9e76-09117bb977cd"
                        },
                        new
                        {
                            UserId = "1ea46bde-c4e1-4461-9abd-d1e213364d3f",
                            RoleId = "71d3eda2-0069-41cc-9e76-09117bb977cd"
                        },
                        new
                        {
                            UserId = "1fe12077-ee83-4362-86e4-136d8368b6a3",
                            RoleId = "e566e2ec-825a-460b-9753-0d4525021d3a"
                        },
                        new
                        {
                            UserId = "b7e58ae5-8976-401d-8e09-919e59f2266b",
                            RoleId = "e566e2ec-825a-460b-9753-0d4525021d3a"
                        },
                        new
                        {
                            UserId = "98988cb5-3ede-4f5a-95ab-34569e24290c",
                            RoleId = "99dd34ef-a62a-447b-9583-1e1ce6bf7723"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubEBook", b =>
                {
                    b.Property<Guid>("EBookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<double>("BorrowPrice")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DownloadCount")
                        .HasColumnType("bigint");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EBookID");

                    b.ToTable("EBooks");

                    b.HasData(
                        new
                        {
                            EBookID = new Guid("7fdcff5d-eea6-4f3d-b79c-60b929b4bf38"),
                            AuthorNames = "Charlotte M. Yonge",
                            Available = true,
                            BorrowPrice = 21.949999999999999,
                            Description = "This book has been considered by academicians and scholars of great significance and value to literature. This forms a part of the knowledge base for future generations. We havent used any OCR or photocopy to produce this book. The whole book has been typeset again to produce it without any errors or poor pictures and errant marks.",
                            DownloadCount = 0L,
                            FilePath = "History-of-France",
                            Genre = "History",
                            PageCount = 78,
                            Price = 89.0,
                            Title = "History of France"
                        },
                        new
                        {
                            EBookID = new Guid("4014ab42-199c-4dc2-ae1e-cfb51bf67b65"),
                            AuthorNames = "Gustave Aimard",
                            Available = true,
                            BorrowPrice = 45.0,
                            Description = "The Pearl of the Andes A Tale of Love and Adventure, a classical book, has been considered important throughout the human history, and so that this work is never forgotten we at Alpha Editions have made efforts in its preservation by republishing this book in a modern format for present and future generations. This whole book has been reformatted, retyped and designed. These books are not made of scanned copies of their original work and hence the text is clear and readable.",
                            DownloadCount = 0L,
                            FilePath = "The-Pearl-of-the-Andes-A-Tale-of-Love-and-Adventure",
                            Genre = "Fantasy Adventure Romance Fiction",
                            PageCount = 205,
                            Price = 111.0,
                            Title = "The Pearl of the Andes A Tale of Love and Adventure"
                        },
                        new
                        {
                            EBookID = new Guid("42973c3a-ea90-4411-bb22-f1ac78dece6a"),
                            AuthorNames = "Gustave Aimard",
                            Available = true,
                            BorrowPrice = 27.0,
                            Description = "This work has been selected by scholars as being culturally important, and is part of the knowledge base of civilization as we know it. This work was reproduced from the original artifact, and remains as true to the original work as possible. Therefore, you will see the original copyright references, library stamps (as most of these works have been housed in our most important libraries around the world), and other notations in the work.This work is in the public domain in the United States of America, and possibly other nations. Within the United States, you may freely copy and distribute this work, as no entity (individual or corporate) has a copyright on the body of the work.As a reproduction of a historical artifact, this work may contain missing or blurred pages, poor pictures, errant marks, etc. Scholars believe, and we concur, that this work is important enough to be preserved, reproduced, and made generally available to the public. We appreciate your support of the preservation process, and thank you for being an important part of keeping this knowledge alive and relevant.",
                            DownloadCount = 0L,
                            FilePath = "The-Pirates-of-the-Prairies-Adventures-in-the-American-Desert",
                            Genre = "History",
                            PageCount = 250,
                            Price = 89.950000000000003,
                            Title = "The Pirates of the Prairies: Adventures in the American Desert"
                        },
                        new
                        {
                            EBookID = new Guid("49bf65b3-8cdc-4688-b955-7035d1e516b0"),
                            AuthorNames = "Gustave Aimard",
                            Available = true,
                            BorrowPrice = 55.0,
                            Description = "The action and adventure genre in fiction depicts events or a series of events that happen outside the ordinary course of the protagonist's daily life, generally accompanied by dangerous episodes and physical action. Adventure stories are quick moving, with the pace of the plot being a critical component of mood setting. Action and adventure have been common book themes since the earliest days of fiction writing. In fact, the plots of Medieval romances were comprised of a series of adventures. Action / adventure fiction often overlaps with other genres, such as: war novels, crime novels, sea stories, Robinsonades, and spy stories.",
                            DownloadCount = 0L,
                            FilePath = "The-Bee-Hunters-A-Tale-of-Adventure",
                            Genre = "Action Adventure Fiction",
                            PageCount = 240,
                            Price = 132.94999999999999,
                            Title = "The Bee Hunters: A Tale of Adventure"
                        },
                        new
                        {
                            EBookID = new Guid("88e2d267-89b3-4289-afe3-13cde4b5ee37"),
                            AuthorNames = "Gustave Aimard",
                            Available = true,
                            BorrowPrice = 51.0,
                            Description = "\"The Smuggler Chief\" is a thrilling adventure story penned by French writer Gustave Aimard and translated by Lascelles Sir Wraxall. Set against a backdrop of danger and intrigue, the novel follows the lives of smugglers, exploring themes of loyalty, betrayal, and the quest for freedom. Aimard's vivid storytelling and rich characterization make this a must-read for fans of classic adventure tales.",
                            DownloadCount = 0L,
                            FilePath = "The-Smuggler-Chief",
                            Genre = "Thriller Adventure Fiction",
                            PageCount = 105,
                            Price = 171.0,
                            Title = "The Smuggler Chief"
                        },
                        new
                        {
                            EBookID = new Guid("c8267340-f844-4c33-a19c-61c7fd2c3f65"),
                            AuthorNames = "Gustave Aimard",
                            Available = true,
                            BorrowPrice = 45.0,
                            Description = "Gustave Aimard, seudónimo de Olivier Groux (1818-1883), fue un novelista francés. Abandonado al nacer por sus padres, de espíritu rebelde, no aceptó a la pareja que lo adoptó y a los nueve años escapó de la casa y marchó a América del Sur. Posteriormente se trasladó a Estados Unidos, donde convivió con los cheyennes. De vuelta la Europa en 1847 viajó por España, Turquía y el Cáucaso. En 1852 volvió a América, pero en 1854 regresó definitivamente a Francia y comenzó a escribir a partir de 1856. Sus experiencias le sirvieron para escribir numerosas novelas del oeste que se hicieron muy populares en Francia y Estados Unidos.",
                            DownloadCount = 0L,
                            FilePath = "Las-noches-mejicanas",
                            Genre = "Thriller Adventure Fiction",
                            PageCount = 240,
                            Price = 159.94999999999999,
                            Title = "Las noches mejicanas"
                        },
                        new
                        {
                            EBookID = new Guid("cfefa5e0-0be9-4a62-b27c-f2058220ba9c"),
                            AuthorNames = "Gustave Aimard",
                            Available = true,
                            BorrowPrice = 9.0,
                            Description = "The Heir of Redclyffe tells the story of Guy Morville, heir to the Redclyffe estate and baronetcy, and his cousin Philip Morville, a conceited hypocrite who enjoys an unwarrantedly high reputation, and of the two sisters whom they love, Amabel and Laura. When Guy raises money to secretly pay off the debts of his blackguard uncle, Philip spreads the rumour that Guy is a reckless gambler. As a result Guy's proposed marriage to Amabel (Amy), who is his guardian's daughter, is called off and he is disowned by his guardian. Guy bears the situation with a new-found Christian fortitude until the uncle clears his character, enabling him to marry Amy after all. They honeymoon in Italy, finding Philip there suffering from a life-threatening fever. Guy nurses him back to health, but catches the fever himself and dies. Philip, transformed by contrition, inherits Redclyffe and marries Laura. Amy has a daughter after her husband's death and says she is happy in her Christian faith and with her daughter.",
                            DownloadCount = 0L,
                            FilePath = "The-Heir-of-Redclyffe",
                            Genre = "Thriller French Adventure",
                            PageCount = 574,
                            Price = 19.949999999999999,
                            Title = "The Heir of Redclyffe"
                        },
                        new
                        {
                            EBookID = new Guid("802c8048-63d7-4f2a-8f19-dbfd8207c623"),
                            AuthorNames = "Gustave Aimard",
                            Available = true,
                            BorrowPrice = 23.0,
                            Description = "The action and adventure genre in fiction depicts events or a series of events that happen outside the ordinary course of the protagonist's daily life, generally accompanied by dangerous episodes and physical action. Adventure stories are quick moving, with the pace of the plot being a critical component of mood setting. Action and adventure have been common book themes since the earliest days of fiction writing. In fact, the plots of Medieval romances were comprised of a series of adventures. Action / adventure fiction often overlaps with other genres, such as: war novels, crime novels, sea stories, Robinsonades, and spy stories.",
                            DownloadCount = 0L,
                            FilePath = "The-Bee-Hunters-A-Tale-of-Adventure",
                            Genre = "Adventure",
                            PageCount = 240,
                            Price = 66.950000000000003,
                            Title = "The Bee Hunters: A Tale of Adventure"
                        });
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubLog", b =>
                {
                    b.Property<Guid>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("LogID");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubPublisher", b =>
                {
                    b.Property<Guid>("PublisherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PublisherID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            PublisherID = new Guid("b828c87a-9eb6-45be-bcf8-bbaa1925971c"),
                            ApplicationUserId = "b4665254-1122-480e-9473-7a945a0c753e",
                            Name = "Forlaget Mellemgaard"
                        },
                        new
                        {
                            PublisherID = new Guid("400546fd-a965-413c-8f09-b0bf04c5acc9"),
                            ApplicationUserId = "1ea46bde-c4e1-4461-9abd-d1e213364d3f",
                            Name = "Buster Nordic"
                        });
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubReader", b =>
                {
                    b.Property<Guid>("ReaderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReaderID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Readers");

                    b.HasData(
                        new
                        {
                            ReaderID = new Guid("aba8c345-3d08-4d90-b64b-fe34d65b9776"),
                            ApplicationUserId = "1fe12077-ee83-4362-86e4-136d8368b6a3"
                        },
                        new
                        {
                            ReaderID = new Guid("c388c882-ff34-4dfc-80ae-86dc2682d16c"),
                            ApplicationUserId = "b7e58ae5-8976-401d-8e09-919e59f2266b"
                        });
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubReceipt", b =>
                {
                    b.Property<Guid>("ReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Acquired")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ReceiptID");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubSubscription", b =>
                {
                    b.Property<Guid>("SubscriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubscriptionID");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            SubscriptionID = new Guid("a9a119ff-82ed-4acf-99be-3afe3519e66d"),
                            Active = true,
                            EndDate = new DateTime(2024, 5, 13, 10, 11, 16, 299, DateTimeKind.Local).AddTicks(7033),
                            Message = "This mounth we are running a campain to spread the love. so subscripe today to get all thoes juicy details",
                            Price = 119.95,
                            StartDate = new DateTime(2024, 4, 13, 10, 11, 16, 299, DateTimeKind.Local).AddTicks(6909),
                            Title = "Romance Mounth"
                        },
                        new
                        {
                            SubscriptionID = new Guid("11fea985-f34a-4167-beed-505643d9d27f"),
                            Active = true,
                            EndDate = new DateTime(2024, 5, 13, 10, 11, 16, 299, DateTimeKind.Local).AddTicks(7067),
                            Message = "Bored? Well do we have some excitement for you, right now we are running a special campain to get that excitement back into peoples lifes",
                            Price = 100.0,
                            StartDate = new DateTime(2024, 4, 13, 10, 11, 16, 299, DateTimeKind.Local).AddTicks(7062),
                            Title = "Fantasy Hype"
                        },
                        new
                        {
                            SubscriptionID = new Guid("83eaede9-0bcb-4e65-b69c-3a87e208d295"),
                            Active = true,
                            EndDate = new DateTime(2024, 5, 13, 10, 11, 16, 299, DateTimeKind.Local).AddTicks(7090),
                            Message = "Want to learn? Well read some of our History books",
                            Price = 45.0,
                            StartDate = new DateTime(2024, 4, 13, 10, 11, 16, 299, DateTimeKind.Local).AddTicks(7074),
                            Title = "Book worm"
                        },
                        new
                        {
                            SubscriptionID = new Guid("26c93320-1dc4-4571-bc12-d5f086a7e4dc"),
                            Active = true,
                            EndDate = new DateTime(2024, 6, 13, 10, 11, 16, 299, DateTimeKind.Local).AddTicks(7110),
                            Message = "My colliction of books i need for school",
                            Price = 49.950000000000003,
                            StartDate = new DateTime(2024, 4, 13, 10, 11, 16, 299, DateTimeKind.Local).AddTicks(7105),
                            Title = "School books"
                        });
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubEBookPubHubPublisher", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PubHubEBookEBookID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PubHubPublisherPublisherID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("PubHubEBookEBookID");

                    b.HasIndex("PubHubPublisherPublisherID");

                    b.ToTable("EBookPublishers");

                    b.HasData(
                        new
                        {
                            ID = new Guid("7fa90e95-93f5-4f6f-b20e-dabe8bd7748a"),
                            PubHubEBookEBookID = new Guid("7fdcff5d-eea6-4f3d-b79c-60b929b4bf38"),
                            PubHubPublisherPublisherID = new Guid("b828c87a-9eb6-45be-bcf8-bbaa1925971c")
                        },
                        new
                        {
                            ID = new Guid("8d030ebd-c5c2-41f0-ab3f-39e424217ab1"),
                            PubHubEBookEBookID = new Guid("4014ab42-199c-4dc2-ae1e-cfb51bf67b65"),
                            PubHubPublisherPublisherID = new Guid("b828c87a-9eb6-45be-bcf8-bbaa1925971c")
                        },
                        new
                        {
                            ID = new Guid("b55f6abc-457b-40a0-aae6-ab35bb37dcc8"),
                            PubHubEBookEBookID = new Guid("49bf65b3-8cdc-4688-b955-7035d1e516b0"),
                            PubHubPublisherPublisherID = new Guid("b828c87a-9eb6-45be-bcf8-bbaa1925971c")
                        },
                        new
                        {
                            ID = new Guid("9f2c3c3a-c5b7-4c8a-aefa-1782eac03637"),
                            PubHubEBookEBookID = new Guid("88e2d267-89b3-4289-afe3-13cde4b5ee37"),
                            PubHubPublisherPublisherID = new Guid("400546fd-a965-413c-8f09-b0bf04c5acc9")
                        },
                        new
                        {
                            ID = new Guid("3cb443b2-0dc6-4848-b5f0-419e875b2e9d"),
                            PubHubEBookEBookID = new Guid("c8267340-f844-4c33-a19c-61c7fd2c3f65"),
                            PubHubPublisherPublisherID = new Guid("400546fd-a965-413c-8f09-b0bf04c5acc9")
                        },
                        new
                        {
                            ID = new Guid("584cd805-6e80-4912-a729-f04c3b7843fd"),
                            PubHubEBookEBookID = new Guid("cfefa5e0-0be9-4a62-b27c-f2058220ba9c"),
                            PubHubPublisherPublisherID = new Guid("400546fd-a965-413c-8f09-b0bf04c5acc9")
                        },
                        new
                        {
                            ID = new Guid("33a56c83-6f6b-4f44-ad46-9133e89c0ec0"),
                            PubHubEBookEBookID = new Guid("802c8048-63d7-4f2a-8f19-dbfd8207c623"),
                            PubHubPublisherPublisherID = new Guid("400546fd-a965-413c-8f09-b0bf04c5acc9")
                        });
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubEBookPubHubReader", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PubHubEBookEBookID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PubHubReaderReaderID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("PubHubEBookEBookID");

                    b.HasIndex("PubHubReaderReaderID");

                    b.ToTable("EBookReaders");

                    b.HasData(
                        new
                        {
                            ID = new Guid("4250dc9b-8908-4044-8011-80444f5e9f36"),
                            PubHubEBookEBookID = new Guid("88e2d267-89b3-4289-afe3-13cde4b5ee37"),
                            PubHubReaderReaderID = new Guid("aba8c345-3d08-4d90-b64b-fe34d65b9776")
                        },
                        new
                        {
                            ID = new Guid("b56ad657-c56b-4b09-af7c-066cb2b9dc91"),
                            PubHubEBookEBookID = new Guid("c8267340-f844-4c33-a19c-61c7fd2c3f65"),
                            PubHubReaderReaderID = new Guid("aba8c345-3d08-4d90-b64b-fe34d65b9776")
                        },
                        new
                        {
                            ID = new Guid("708ae1cd-b7ec-4a30-a120-ad7867e316bd"),
                            PubHubEBookEBookID = new Guid("cfefa5e0-0be9-4a62-b27c-f2058220ba9c"),
                            PubHubReaderReaderID = new Guid("c388c882-ff34-4dfc-80ae-86dc2682d16c")
                        },
                        new
                        {
                            ID = new Guid("f1aa22be-b260-4b1c-8517-9d587d42f98c"),
                            PubHubEBookEBookID = new Guid("c8267340-f844-4c33-a19c-61c7fd2c3f65"),
                            PubHubReaderReaderID = new Guid("c388c882-ff34-4dfc-80ae-86dc2682d16c")
                        },
                        new
                        {
                            ID = new Guid("1114142e-8763-4e68-89cf-ab0a9349c123"),
                            PubHubEBookEBookID = new Guid("42973c3a-ea90-4411-bb22-f1ac78dece6a"),
                            PubHubReaderReaderID = new Guid("c388c882-ff34-4dfc-80ae-86dc2682d16c")
                        });
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubEBookPubHubSubscription", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PubHubEBookEBookID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PubHubSubscriptionSubscriptionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("PubHubEBookEBookID");

                    b.HasIndex("PubHubSubscriptionSubscriptionID");

                    b.ToTable("EBookSubscriptions");

                    b.HasData(
                        new
                        {
                            ID = new Guid("f1e5f3cc-355e-4f9f-9973-ca3f380eed3a"),
                            PubHubEBookEBookID = new Guid("4014ab42-199c-4dc2-ae1e-cfb51bf67b65"),
                            PubHubSubscriptionSubscriptionID = new Guid("a9a119ff-82ed-4acf-99be-3afe3519e66d")
                        },
                        new
                        {
                            ID = new Guid("e02162c6-be18-4a3f-835e-08333c51d34a"),
                            PubHubEBookEBookID = new Guid("42973c3a-ea90-4411-bb22-f1ac78dece6a"),
                            PubHubSubscriptionSubscriptionID = new Guid("83eaede9-0bcb-4e65-b69c-3a87e208d295")
                        },
                        new
                        {
                            ID = new Guid("9cefc482-5442-49ef-804e-83929901c6a1"),
                            PubHubEBookEBookID = new Guid("7fdcff5d-eea6-4f3d-b79c-60b929b4bf38"),
                            PubHubSubscriptionSubscriptionID = new Guid("83eaede9-0bcb-4e65-b69c-3a87e208d295")
                        },
                        new
                        {
                            ID = new Guid("daf5ffe9-9393-4faa-9767-7f274d925bbd"),
                            PubHubEBookEBookID = new Guid("49bf65b3-8cdc-4688-b955-7035d1e516b0"),
                            PubHubSubscriptionSubscriptionID = new Guid("11fea985-f34a-4167-beed-505643d9d27f")
                        },
                        new
                        {
                            ID = new Guid("cd8c36b1-d8a1-4fb8-84bb-62572d38dc7c"),
                            PubHubEBookEBookID = new Guid("88e2d267-89b3-4289-afe3-13cde4b5ee37"),
                            PubHubSubscriptionSubscriptionID = new Guid("11fea985-f34a-4167-beed-505643d9d27f")
                        },
                        new
                        {
                            ID = new Guid("7d89a8be-6110-4b7a-bf59-b8d9f46d7d35"),
                            PubHubEBookEBookID = new Guid("c8267340-f844-4c33-a19c-61c7fd2c3f65"),
                            PubHubSubscriptionSubscriptionID = new Guid("11fea985-f34a-4167-beed-505643d9d27f")
                        },
                        new
                        {
                            ID = new Guid("54390f5b-3f3d-4d33-882b-759ef95fe3b3"),
                            PubHubEBookEBookID = new Guid("cfefa5e0-0be9-4a62-b27c-f2058220ba9c"),
                            PubHubSubscriptionSubscriptionID = new Guid("11fea985-f34a-4167-beed-505643d9d27f")
                        },
                        new
                        {
                            ID = new Guid("ac9b8d11-d901-4684-98e3-9abbb45b7f28"),
                            PubHubEBookEBookID = new Guid("802c8048-63d7-4f2a-8f19-dbfd8207c623"),
                            PubHubSubscriptionSubscriptionID = new Guid("11fea985-f34a-4167-beed-505643d9d27f")
                        });
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubSubscriptionPubHubReader", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PubHubReaderReaderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PubHubSubscriptionSubscriptionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("PubHubReaderReaderID");

                    b.HasIndex("PubHubSubscriptionSubscriptionID");

                    b.ToTable("SubscriptionReaders");

                    b.HasData(
                        new
                        {
                            ID = new Guid("d2aa90c7-f798-49e5-8c26-a19bd6b22c8b"),
                            PubHubReaderReaderID = new Guid("c388c882-ff34-4dfc-80ae-86dc2682d16c"),
                            PubHubSubscriptionSubscriptionID = new Guid("26c93320-1dc4-4571-bc12-d5f086a7e4dc")
                        });
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubSupscriptionPubHubPublisher", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PubHubPublisherPublisherID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PubHubSubscriptionSubscriptionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("PubHubPublisherPublisherID");

                    b.HasIndex("PubHubSubscriptionSubscriptionID");

                    b.ToTable("SubscriptionPublishers");

                    b.HasData(
                        new
                        {
                            ID = new Guid("d6bd33c2-5d93-4f65-8b59-43231af06c6a"),
                            PubHubPublisherPublisherID = new Guid("b828c87a-9eb6-45be-bcf8-bbaa1925971c"),
                            PubHubSubscriptionSubscriptionID = new Guid("a9a119ff-82ed-4acf-99be-3afe3519e66d")
                        },
                        new
                        {
                            ID = new Guid("90d11d08-e86d-4e9c-b7b7-eb0e07463e47"),
                            PubHubPublisherPublisherID = new Guid("b828c87a-9eb6-45be-bcf8-bbaa1925971c"),
                            PubHubSubscriptionSubscriptionID = new Guid("83eaede9-0bcb-4e65-b69c-3a87e208d295")
                        },
                        new
                        {
                            ID = new Guid("609a7401-d2f4-4ec4-b020-24f34611853f"),
                            PubHubPublisherPublisherID = new Guid("400546fd-a965-413c-8f09-b0bf04c5acc9"),
                            PubHubSubscriptionSubscriptionID = new Guid("11fea985-f34a-4167-beed-505643d9d27f")
                        });
                });

            modelBuilder.Entity("PubHubWebServer.Data.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("MyPubHubAccount")
                        .HasColumnType("uniqueidentifier");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "b4665254-1122-480e-9473-7a945a0c753e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0c400bbe-b021-4aeb-847b-4b7d4ce75670",
                            Email = "Mellemgaard@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "MELLEMGAARD@HOTMAIL.COM",
                            NormalizedUserName = "MELLEMGAARD@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEK9f2/r5mppj71oIdnTmhl3Q2uZH6xsnNBP4hi5XqYdMRLah/wmwuduI3bljOvCBDg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0db19f29-48dd-45a7-b042-06538432fe1e",
                            TwoFactorEnabled = false,
                            UserName = "Mellemgaard@hotmail.com",
                            Active = true,
                            MyPubHubAccount = new Guid("b828c87a-9eb6-45be-bcf8-bbaa1925971c")
                        },
                        new
                        {
                            Id = "1ea46bde-c4e1-4461-9abd-d1e213364d3f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dbd7ee92-2dd8-4a96-a818-5703da528c8a",
                            Email = "Nordic@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "NORDIC@HOTMAIL.COM",
                            NormalizedUserName = "NORDIC@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC03VHK6A1NtEMAQ6QL+bohjRzm5uDkmU+lVP79Wrm6vjLpQrVSiDw09lKUJ/WaP0A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "733572b8-6326-4ae0-84c2-7c2b1618b4d8",
                            TwoFactorEnabled = false,
                            UserName = "Nordic@hotmail.com",
                            Active = true,
                            MyPubHubAccount = new Guid("400546fd-a965-413c-8f09-b0bf04c5acc9")
                        },
                        new
                        {
                            Id = "1fe12077-ee83-4362-86e4-136d8368b6a3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ee7d0cda-8322-4ef4-8b97-ed0ba753d825",
                            Email = "lukas3302@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "LUKAS3302@HOTMAIL.COM",
                            NormalizedUserName = "LUKAS3302@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECLK5z7dBmyTmq4aP3+9dxAZpU9stSgAv8UUnQi4U5h3EC4Rpl3MZwPUE6JnKc3n4w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "20b8b6b2-5690-442a-9f1e-80f3801b7d55",
                            TwoFactorEnabled = false,
                            UserName = "lukas3302@hotmail.com",
                            Active = true,
                            MyPubHubAccount = new Guid("aba8c345-3d08-4d90-b64b-fe34d65b9776")
                        },
                        new
                        {
                            Id = "b7e58ae5-8976-401d-8e09-919e59f2266b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "76a85aa0-67fa-457b-bcae-7f9b5744fe30",
                            Email = "Jens2837@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "JENS2837@HOTMAIL.COM",
                            NormalizedUserName = "JENS2837@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFrQFmrsx5BNODONICue+VlQCa1Pn6D2QElzCnGTeC6fG+z0Jkk5onyysaZdVXz3ow==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "371fcebe-3aef-4c68-baf6-3d6ba68866a0",
                            TwoFactorEnabled = false,
                            UserName = "jens2837@hotmail.com",
                            Active = true,
                            MyPubHubAccount = new Guid("c388c882-ff34-4dfc-80ae-86dc2682d16c")
                        },
                        new
                        {
                            Id = "98988cb5-3ede-4f5a-95ab-34569e24290c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "afc9708f-9d69-4980-8b21-906cf1a238ae",
                            Email = "Admin@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@HOTMAIL.COM",
                            NormalizedUserName = "ADMIN@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFCqc3UUv17n7nBkGVyngPfWnKaieHGQKiwh9eguL4xvZCY13Cd35xIWTTihCm5ckA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7d2c2a45-fafc-402d-8d86-f5397ec1d237",
                            TwoFactorEnabled = false,
                            UserName = "Admin@hotmail.com",
                            Active = true,
                            MyPubHubAccount = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.HasOne("PubHubWebServer.Data.ApplicationUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubPublisher", b =>
                {
                    b.HasOne("PubHubWebServer.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubReader", b =>
                {
                    b.HasOne("PubHubWebServer.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubEBookPubHubPublisher", b =>
                {
                    b.HasOne("PubHubWebServer.Data.Models.PubHubEBook", null)
                        .WithMany("Publishers")
                        .HasForeignKey("PubHubEBookEBookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PubHubWebServer.Data.Models.PubHubPublisher", null)
                        .WithMany("EBooks")
                        .HasForeignKey("PubHubPublisherPublisherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubEBookPubHubReader", b =>
                {
                    b.HasOne("PubHubWebServer.Data.Models.PubHubEBook", null)
                        .WithMany("Readers")
                        .HasForeignKey("PubHubEBookEBookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PubHubWebServer.Data.Models.PubHubReader", null)
                        .WithMany("EBooks")
                        .HasForeignKey("PubHubReaderReaderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubEBookPubHubSubscription", b =>
                {
                    b.HasOne("PubHubWebServer.Data.Models.PubHubEBook", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("PubHubEBookEBookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PubHubWebServer.Data.Models.PubHubSubscription", null)
                        .WithMany("EBooks")
                        .HasForeignKey("PubHubSubscriptionSubscriptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubSubscriptionPubHubReader", b =>
                {
                    b.HasOne("PubHubWebServer.Data.Models.PubHubReader", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("PubHubReaderReaderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PubHubWebServer.Data.Models.PubHubSubscription", null)
                        .WithMany("Reader")
                        .HasForeignKey("PubHubSubscriptionSubscriptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubSupscriptionPubHubPublisher", b =>
                {
                    b.HasOne("PubHubWebServer.Data.Models.PubHubPublisher", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("PubHubPublisherPublisherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PubHubWebServer.Data.Models.PubHubSubscription", null)
                        .WithMany("Publisher")
                        .HasForeignKey("PubHubSubscriptionSubscriptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubEBook", b =>
                {
                    b.Navigation("Publishers");

                    b.Navigation("Readers");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubPublisher", b =>
                {
                    b.Navigation("EBooks");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubReader", b =>
                {
                    b.Navigation("EBooks");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubSubscription", b =>
                {
                    b.Navigation("EBooks");

                    b.Navigation("Publisher");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("PubHubWebServer.Data.ApplicationUser", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
