// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PubHubWebServer.Data;

#nullable disable

namespace PubHubWebServer.Migrations
{
    [DbContext(typeof(PubHubDBContext))]
    [Migration("20240407154919_UserPublisherReaderBooksDataSeeding")]
    partial class UserPublisherReaderBooksDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubEBook", b =>
                {
                    b.Property<Guid>("EBookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BorrowPrice")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DownloadCount")
                        .HasColumnType("bigint");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EBookID");

                    b.ToTable("EBooks");

                    b.HasData(
                        new
                        {
                            EBookID = new Guid("66666e12-98aa-40d9-b1cd-5977e40e6002"),
                            AuthorNames = "Charlotte M. Yonge",
                            BorrowPrice = 65.950000000000003,
                            Description = "Richard I (28 August 933 – 20 November 996), also known as Richard the Fearless (French, Richard Sans-Peur), was the Count of Rouen from 942 to 996. Dudo of Saint-Quentin, whom Richard commissioned to write the \"De moribus et actis primorum Normanniae ducum\" (Latin, \"On the Customs and Deeds of the First Dukes of Normandy\"), called him a Dux.",
                            DownloadCount = 0L,
                            FilePath = "The-Little-Duke-Richard-the-Fearless",
                            Genre = "History",
                            PageCount = 145,
                            Price = 130.94999999999999,
                            Title = "The Little Duke: Richard the Fearless"
                        },
                        new
                        {
                            EBookID = new Guid("7b6bb5f6-0238-4304-8508-6e9b130a6bc6"),
                            AuthorNames = "Charlotte M. Yonge",
                            BorrowPrice = 34.0,
                            Description = "First published in 1853, The Heir of Redclyffe was the most successful novel of the century. Adopted by William Morris and Burne-Jones \"as a pattern for life,\" the protagonist, Guy, was a popular role model of noble virtue, while another character, Amy, was seen as the ideal Victorian wife--redeemer and inspirer, supporter and guide. This novel is a virtual paradigm of the trends of thought which marked the middle decades of the nineteenth-century. It is also deeply marked by the influence of the Oxford Movement, an aspect explored in Barbara Dennis's Introduction to this unique critical edition.",
                            DownloadCount = 0L,
                            FilePath = "The-Heir-of-Redclyffe",
                            Genre = "Romance novel",
                            PageCount = 637,
                            Price = 170.0,
                            Title = "The Heir of Redclyffe"
                        },
                        new
                        {
                            EBookID = new Guid("13bc304c-5e54-47e0-9f6e-a4bfd4f14412"),
                            AuthorNames = "Charlotte M. Yonge",
                            BorrowPrice = 21.949999999999999,
                            Description = "This book has been considered by academicians and scholars of great significance and value to literature. This forms a part of the knowledge base for future generations. We havent used any OCR or photocopy to produce this book. The whole book has been typeset again to produce it without any errors or poor pictures and errant marks.",
                            DownloadCount = 0L,
                            FilePath = "History-of-France",
                            Genre = "History",
                            PageCount = 78,
                            Price = 89.0,
                            Title = "History of France"
                        },
                        new
                        {
                            EBookID = new Guid("a6a236ed-7b6b-4159-9e1e-10572be599ef"),
                            AuthorNames = "Gustave Aimard",
                            BorrowPrice = 45.0,
                            Description = "The Pearl of the Andes A Tale of Love and Adventure, a classical book, has been considered important throughout the human history, and so that this work is never forgotten we at Alpha Editions have made efforts in its preservation by republishing this book in a modern format for present and future generations. This whole book has been reformatted, retyped and designed. These books are not made of scanned copies of their original work and hence the text is clear and readable.",
                            DownloadCount = 0L,
                            FilePath = "The-Pearl-of-the-Andes-A-Tale-of-Love-and-Adventure",
                            Genre = "Fantasy Adventure Romance Fiction",
                            PageCount = 205,
                            Price = 111.0,
                            Title = "The Pearl of the Andes A Tale of Love and Adventure"
                        },
                        new
                        {
                            EBookID = new Guid("485b92db-4fc2-49e6-bb0e-dde12042dd35"),
                            AuthorNames = "Gustave Aimard",
                            BorrowPrice = 27.0,
                            Description = "This work has been selected by scholars as being culturally important, and is part of the knowledge base of civilization as we know it. This work was reproduced from the original artifact, and remains as true to the original work as possible. Therefore, you will see the original copyright references, library stamps (as most of these works have been housed in our most important libraries around the world), and other notations in the work.This work is in the public domain in the United States of America, and possibly other nations. Within the United States, you may freely copy and distribute this work, as no entity (individual or corporate) has a copyright on the body of the work.As a reproduction of a historical artifact, this work may contain missing or blurred pages, poor pictures, errant marks, etc. Scholars believe, and we concur, that this work is important enough to be preserved, reproduced, and made generally available to the public. We appreciate your support of the preservation process, and thank you for being an important part of keeping this knowledge alive and relevant.",
                            DownloadCount = 0L,
                            FilePath = "The-Pirates-of-the-Prairies-Adventures-in-the-American-Desert",
                            Genre = "History",
                            PageCount = 250,
                            Price = 89.950000000000003,
                            Title = "The Pirates of the Prairies: Adventures in the American Desert"
                        },
                        new
                        {
                            EBookID = new Guid("d5f45ec5-110e-4be6-9f85-70d864307cf3"),
                            AuthorNames = "Gustave Aimard",
                            BorrowPrice = 55.0,
                            Description = "The action and adventure genre in fiction depicts events or a series of events that happen outside the ordinary course of the protagonist's daily life, generally accompanied by dangerous episodes and physical action. Adventure stories are quick moving, with the pace of the plot being a critical component of mood setting. Action and adventure have been common book themes since the earliest days of fiction writing. In fact, the plots of Medieval romances were comprised of a series of adventures. Action / adventure fiction often overlaps with other genres, such as: war novels, crime novels, sea stories, Robinsonades, and spy stories.",
                            DownloadCount = 0L,
                            FilePath = "The-Bee-Hunters-A-Tale-of-Adventure",
                            Genre = "Action Adventure Fiction",
                            PageCount = 240,
                            Price = 132.94999999999999,
                            Title = "The Bee Hunters: A Tale of Adventure"
                        },
                        new
                        {
                            EBookID = new Guid("cafd2842-51d6-4bd5-9a6c-08c4aa665cc9"),
                            AuthorNames = "Gustave Aimard",
                            BorrowPrice = 51.0,
                            Description = "\"The Smuggler Chief\" is a thrilling adventure story penned by French writer Gustave Aimard and translated by Lascelles Sir Wraxall. Set against a backdrop of danger and intrigue, the novel follows the lives of smugglers, exploring themes of loyalty, betrayal, and the quest for freedom. Aimard's vivid storytelling and rich characterization make this a must-read for fans of classic adventure tales.",
                            DownloadCount = 0L,
                            FilePath = "The-Smuggler-Chief",
                            Genre = "Thriller Adventure Fiction",
                            PageCount = 105,
                            Price = 171.0,
                            Title = "The Smuggler Chief"
                        },
                        new
                        {
                            EBookID = new Guid("c2571b34-63d0-4faf-ac49-1d177a4a22c8"),
                            AuthorNames = "Gustave Aimard",
                            BorrowPrice = 45.0,
                            Description = "Gustave Aimard, seudónimo de Olivier Groux (1818-1883), fue un novelista francés. Abandonado al nacer por sus padres, de espíritu rebelde, no aceptó a la pareja que lo adoptó y a los nueve años escapó de la casa y marchó a América del Sur. Posteriormente se trasladó a Estados Unidos, donde convivió con los cheyennes. De vuelta la Europa en 1847 viajó por España, Turquía y el Cáucaso. En 1852 volvió a América, pero en 1854 regresó definitivamente a Francia y comenzó a escribir a partir de 1856. Sus experiencias le sirvieron para escribir numerosas novelas del oeste que se hicieron muy populares en Francia y Estados Unidos.",
                            DownloadCount = 0L,
                            FilePath = "Las-noches-mejicanas",
                            Genre = "Thriller Adventure Fiction",
                            PageCount = 240,
                            Price = 159.94999999999999,
                            Title = "Las noches mejicanas"
                        },
                        new
                        {
                            EBookID = new Guid("6ccbb8a7-1472-4395-8834-4179c3ec13e4"),
                            AuthorNames = "Gustave Aimard",
                            BorrowPrice = 89.950000000000003,
                            Description = "\"The Flying Horseman\" is a thrilling tale penned by the French writer Gustave Aimard. Set in a world of adventure and danger, the story follows the journey of its titular character as he navigates challenges and confronts adversaries. With its gripping narrative and rich character development, this classic work is a testament to Aimard's literary genius.",
                            DownloadCount = 0L,
                            FilePath = "",
                            Genre = "Thriller French Adventure",
                            PageCount = 166,
                            Price = 299.94999999999999,
                            Title = "The Flying Horseman"
                        },
                        new
                        {
                            EBookID = new Guid("9dfe7001-ff62-49c2-a119-20a8551aca67"),
                            AuthorNames = "Gustave Aimard",
                            BorrowPrice = 43.0,
                            Description = "Opening with loading a ship in Cape Horn, Chile, the book takes readers on an adventure throughout South America. Encounters with indigenous populations and learning to find common ground with others are at the heart of this tale, in many ways mirroring the author's own experiences.",
                            DownloadCount = 0L,
                            FilePath = "",
                            Genre = "Fiction Adventure",
                            PageCount = 190,
                            Price = 206.94999999999999,
                            Title = "The Guide of the Desert"
                        });
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubLog", b =>
                {
                    b.Property<Guid>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("LogID");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubPublisher", b =>
                {
                    b.Property<Guid>("PublisherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PublisherID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            PublisherID = new Guid("01e6a853-9ed8-4616-8866-1e5244ff240f"),
                            ApplicationUserId = "1921f6ae-86bf-4581-b6b7-cccfd94157b1",
                            Name = "Forlaget Mellemgaard"
                        },
                        new
                        {
                            PublisherID = new Guid("f07370a6-780f-426f-833f-182a1ede9304"),
                            ApplicationUserId = "74fd6a7a-0b9b-4540-bd86-3f2f59ecdbfa",
                            Name = "Buster Nordic"
                        });
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubReader", b =>
                {
                    b.Property<Guid>("ReaderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReaderID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Readers");

                    b.HasData(
                        new
                        {
                            ReaderID = new Guid("d3f64447-bed3-44fb-879e-c989eb81ede0"),
                            ApplicationUserId = "2932e86c-ddf9-4403-a664-7729a9c8b865"
                        },
                        new
                        {
                            ReaderID = new Guid("094e390b-2c8f-4e71-9660-e491993d2b14"),
                            ApplicationUserId = "3fcb39c1-5da6-4a09-8383-a7850ecfd6b2"
                        });
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubReceipt", b =>
                {
                    b.Property<Guid>("ReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Acquired")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ReceiptID");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubSubscription", b =>
                {
                    b.Property<Guid>("SubscriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubscriptionID");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubEBookPubHubPublisher", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EBookID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublisherID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("EBookID");

                    b.HasIndex("PublisherID");

                    b.ToTable("EBookPublishers");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubEBookPubHubReader", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EBookID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReaderID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("EBookID");

                    b.HasIndex("ReaderID");

                    b.ToTable("EBookReaders");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubEBookPubHubSubscription", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EBookID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("EBookID");

                    b.HasIndex("SubscriptionID");

                    b.ToTable("EBookSubscriptions");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubSubscriptionPubHubReader", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReaderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ReaderID");

                    b.HasIndex("SubscriptionID");

                    b.ToTable("PubHubSubscriptionPubHubReader");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubSupscriptionPubHubPublisher", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublisherID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("PublisherID");

                    b.HasIndex("SubscriptionID");

                    b.ToTable("PubHubSupscriptionPubHubPublisher");
                });

            modelBuilder.Entity("PubHubWebServer.Data.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("MyPubHubAccount")
                        .HasColumnType("uniqueidentifier");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "1921f6ae-86bf-4581-b6b7-cccfd94157b1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9b8fdbf6-ed5a-4b82-aaf4-dd4d5e080d52",
                            Email = "Mellemgaard@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MELLEMGAARD@HOTMAIL.COM",
                            NormalizedUserName = "FORLAGET MELLEMGAARD",
                            PasswordHash = "AQAAAAIAAYagAAAAEEmqQe/vndhXqRlDxRsxGHAX1kuWQ117TY6XF/XEO905889tcX+x5AeDq4eyXySWEQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "TBBRBHXVDKL4JYRX5YZLFTX56P76CYKO",
                            TwoFactorEnabled = false,
                            UserName = "Forlaget Mellemgaard",
                            Active = true,
                            MyPubHubAccount = new Guid("01e6a853-9ed8-4616-8866-1e5244ff240f")
                        },
                        new
                        {
                            Id = "74fd6a7a-0b9b-4540-bd86-3f2f59ecdbfa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "653cb2db-6f92-4eda-8288-ec972843ad9d",
                            Email = "Nordic@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NORDIC@HOTMAIL.COM",
                            NormalizedUserName = "BUSTER NORDIC",
                            PasswordHash = "AQAAAAIAAYagAAAAEKpF63VYci9tx6jT7M6RwfqLpgvmA5W8iFFOyOVJZsXZ+5ozXHv+vVhSZ4iBWDHRDA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NQUEGF4VUUD7QGUA4XP5YNMDMLT5US6H",
                            TwoFactorEnabled = false,
                            UserName = "Buster Nordic",
                            Active = true,
                            MyPubHubAccount = new Guid("f07370a6-780f-426f-833f-182a1ede9304")
                        },
                        new
                        {
                            Id = "2932e86c-ddf9-4403-a664-7729a9c8b865",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e82c37ba-22be-4f0a-ac8b-23a62c11476a",
                            Email = "lukas3302@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LUKAS3302@HOTMAIL.COM",
                            NormalizedUserName = "LUKAS",
                            PasswordHash = "AQAAAAIAAYagAAAAEPsl/YnmLOop8Q3eHEXfKy0CTTI7Vpm2pWEn64idVqozxtLVvtcr4Uf1iyRbshmsIw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "GLY234PA27LVMGEQEBJERG7KGRXQSRDU",
                            TwoFactorEnabled = false,
                            UserName = "Lukas Pedersen",
                            Active = true,
                            MyPubHubAccount = new Guid("d3f64447-bed3-44fb-879e-c989eb81ede0")
                        },
                        new
                        {
                            Id = "3fcb39c1-5da6-4a09-8383-a7850ecfd6b2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d317d42c-6ab7-4ece-b9c4-4210d3c2f009",
                            Email = "Jens2837@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JENS2837@HOTMAIL.COM",
                            NormalizedUserName = "JENS ANKER",
                            PasswordHash = "AQAAAAIAAYagAAAAEH5hcJHlyO7YeqMGmZqDju46u5EHka/NiKKqqJHKpbq3jEiI5UT1tsVlUp4ziDa+5Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "FT4UX4Y6TUBDTMWYUAIVE622QJ6GHBOG",
                            TwoFactorEnabled = false,
                            UserName = "Jens Anker",
                            Active = true,
                            MyPubHubAccount = new Guid("094e390b-2c8f-4e71-9660-e491993d2b14")
                        },
                        new
                        {
                            Id = "8c50d7e9-0cef-4b33-a2e3-002375b85dc2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a4d4b000-df14-4c3e-9f89-73a90c4a8584",
                            Email = "Admin@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@HOTMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEI7YCzKIQOnqgMycVwCJ/45d4njC5tjma1AFeC1Z/YuJ2ZD91x+B90FvXluwB3qZvw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "GP4QLQ2ZVJJBYBHBQLLGP4G22UJJFH4U",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            Active = true,
                            MyPubHubAccount = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.HasOne("PubHubWebServer.Data.ApplicationUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubPublisher", b =>
                {
                    b.HasOne("PubHubWebServer.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubReader", b =>
                {
                    b.HasOne("PubHubWebServer.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubEBookPubHubPublisher", b =>
                {
                    b.HasOne("PubHubWebServer.Data.Models.PubHubEBook", "EBook")
                        .WithMany("Publishers")
                        .HasForeignKey("EBookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PubHubWebServer.Data.Models.PubHubPublisher", "Publisher")
                        .WithMany("EBooks")
                        .HasForeignKey("PublisherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EBook");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubEBookPubHubReader", b =>
                {
                    b.HasOne("PubHubWebServer.Data.Models.PubHubEBook", "EBook")
                        .WithMany("Readers")
                        .HasForeignKey("EBookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PubHubWebServer.Data.Models.PubHubReader", "Reader")
                        .WithMany("EBooks")
                        .HasForeignKey("ReaderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EBook");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubEBookPubHubSubscription", b =>
                {
                    b.HasOne("PubHubWebServer.Data.Models.PubHubEBook", "EBook")
                        .WithMany("Subscriptions")
                        .HasForeignKey("EBookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PubHubWebServer.Data.Models.PubHubSubscription", "Subscription")
                        .WithMany("EBooks")
                        .HasForeignKey("SubscriptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EBook");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubSubscriptionPubHubReader", b =>
                {
                    b.HasOne("PubHubWebServer.Data.Models.PubHubReader", "Reader")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ReaderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PubHubWebServer.Data.Models.PubHubSubscription", "Subscription")
                        .WithMany("Reader")
                        .HasForeignKey("SubscriptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reader");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.Relationships.PubHubSupscriptionPubHubPublisher", b =>
                {
                    b.HasOne("PubHubWebServer.Data.Models.PubHubPublisher", "Publisher")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PublisherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PubHubWebServer.Data.Models.PubHubSubscription", "Subscription")
                        .WithMany("Publisher")
                        .HasForeignKey("SubscriptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publisher");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubEBook", b =>
                {
                    b.Navigation("Publishers");

                    b.Navigation("Readers");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubPublisher", b =>
                {
                    b.Navigation("EBooks");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubReader", b =>
                {
                    b.Navigation("EBooks");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("PubHubWebServer.Data.Models.PubHubSubscription", b =>
                {
                    b.Navigation("EBooks");

                    b.Navigation("Publisher");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("PubHubWebServer.Data.ApplicationUser", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
